version: '2'
services:
  web:
    image: fpfis/httpd-php-dev:7.1
    # image: fpfis/httpd-php-dev:5.6
    # image: fpfis/php56-dev
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
      - ~/.composer/cache:/root/.composer/cache
      - ~/.drush/cache:/root/.drush/cache
    environment:
#      XDEBUG_CONFIG: "idekey=cloud9ide remote_connect_back=0 remote_host=${DOCKER_HOST_IP} remote_enable=1"
#      PHP_IDE_CONFIG: "serverName=Test"
      DOCUMENT_ROOT: "${PWD}/app"
#      VIRTUAL_HOST: {{baseurl}}
#      VIRTUAL_NETWORK: nginx-proxy
    depends_on:
      - mysql
    ports:
      - '80:80'
    networks:
      - default
#      - proxy
  mysql:
    image: percona/percona-server:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'drupal'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpass'
    ports:
      - '3306'
  selenium:
    image: wernight/phantomjs
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
    command: "phantomjs --webdriver=8910 --ignore-ssl-errors=true --ssl-protocol=any"
networks:
  default:
    driver: bridge
#  proxy:
#    external:
#      name: proxy-frontend
